# Generated by Django 4.1.5 on 2023-01-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
