# Generated by Django 4.1.5 on 2023-01-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transactions_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
